name: athlete_py38
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.1=openblas
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py38h6d47a40_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cmake=3.21.3=h8897547_0
  - contourpy=1.1.1=py38h7f3f72f_1
  - cudatoolkit=11.3.1=hb98b00a_13
  - cudatoolkit-dev=11.3.1=py38h497a2fe_0
  - cudnn=8.2.1.32=h86fa8c9_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py38h01eb140_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.2=h59595ed_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.53.1=py38h2019614_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.6.1=pyhff2d567_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py38he82f83a_8
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=23_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=23_linux64_openblas
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.4.0=h251f7ec_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=ha6d2627_1004
  - libgomp=14.1.0=h77fa898_0
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=23_linux64_openblas
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.4=hfdd30dd_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcb278e6_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.20=hf484d3e_1001
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=pyhd8ed1ab_0
  - olefile=0.47=pyhd8ed1ab_0
  - openblas=0.3.27=pthreads_h9eca1d5_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pillow=8.3.2=py38h8e6f84c_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.4=py38hfa26641_0
  - pyqt5-sip=12.9.0=py38hfa26641_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywavelets=1.4.1=py38h7f0c24c_1
  - pyyaml=6.0.2=py38h2019614_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rhash=1.4.3=hd590300_2
  - scikit-image=0.18.1=py38h51da96c_0
  - scipy=1.10.1=py38h32ae08f_1
  - sip=6.5.1=py38h709712a_2
  - sqlite=3.45.3=h5eee18b_0
  - swig=4.1.1=h1bc8f3f_2
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2020.6.3=py_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4.1=py38hfb59056_0
  - unicodedata2=15.1.0=py38h01eb140_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py38ha98ab4e_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.3.1
      - aiosignal==1.3.1
      - akro==0.0.8
      - astunparse==1.6.3
      - attrs==24.2.0
      - cachetools==4.2.4
      - clang==5.0
      - click==8.0.4
      - cloudpickle==1.6.0
      - cma==2.7.0
      - cython==0.29.32
      - decorator==5.1.1
      - distlib==0.3.8
      - dm-tree==0.1.8
      - dowel==0.0.3
      - fasteners==0.19
      - filelock==3.15.4
      - flatbuffers==25.9.23
      - frozenlist==1.4.1
      - gast==0.4.0
      - glfw==2.7.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.65.5
      - gym==0.19.0
      - gym-notices==0.0.8
      - h5py==3.1.0
      - imageio==2.35.0
      - importlib-metadata==8.2.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - keras==2.13.1
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.3.3
      - msgpack==1.0.8
      - mujoco-py==2.1.2.14
      - munpy==0.0.0
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opensim==4.5.1
      - opt-einsum==3.3.0
      - pandas==2.0.3
      - pip==21.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==3.20.3
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pytz==2025.2
      - ray==2.10.0
      - referencing==0.35.1
      - requests-oauthlib==2.0.0
      - rpds-py==0.20.0
      - rsa==4.9
      - setproctitle==1.3.3
      - setuptools==65.5.0
      - six==1.15.0
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.0
      - tensorboardx==2.4
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-probability==0.12.2
      - termcolor==1.1.0
      - torch==1.7.1
      - torchvision==0.8.2
      - typing-extensions==3.7.4.3
      - tzdata==2025.2
      - virtualenv==20.26.3
      - werkzeug==3.0.3
      - wheel==0.38.0
      - wrapt==1.12.1
prefix: /home/lisca/biomec/install/a202406/envs/athlete_py38
