name: opensim_py311
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cmake=3.30.5=hf9cb763_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=8.10.1=hbbe4b11_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.0=hadc24fc_1
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.2=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - pcre2=10.42=hcad00b1_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.10=hc5c86c4_3_cpython
  - readline=8.2=h5eee18b_0
  - rhash=1.4.5=hb9d3cd8_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.47.0=h9eae976_1
  - swig=4.1.1=h1bc8f3f_2
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - numpy==2.1.2
prefix: /home/lisca/biomec/install/a202406/envs/opensim_py311
